# Generated by Django 2.0.3 on 2018-03-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='slug',
            field=models.SlugField(default='hola', unique=True),
            preserve_default=False,
        ),
    ]
